# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find intervals containing a set of points
#'
#' @param pos Integer vector of positions
#' @param start Integer vector with left endpoints of intervals
#' @param end Integer vector with right endpoints of intervals
#'
#' @return
#' A list with two elements named "position" and "interval".  Both
#' are integer vectors of indexes.  The "position" vector indexes the
#' `pos` argument and the "interval" vector the `start` and `end`
#' arguments.  The kth index in the "position" vector forms a pair
#' with the kth index in the "interval" vector.  A pair of indexes
#' (i,j) means that \code{pos[i]} belongs to the interval defined by
#' \code{start[j]} and \code{end[j]}.
#'
#' @examples
#' rcpp_find_matching_intervals(1:3, 2:3, 4:5)
#'
#' @export
rcpp_find_matching_intervals <- function(pos, start, end) {
    .Call('miscFun_rcpp_find_matching_intervals', PACKAGE = 'miscFun', pos, start, end)
}

