# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find intervals containing a set of points
#'
#' @param pos Double vector of positions
#' @param start Double vector with left endpoints of intervals
#' @param end Double vector with right endpoints of intervals
#'
#' @return
#' A list with elements "position" and "interval".  Both are integer
#' vectors containing indexes.  The "position" vector indexes the
#' \code{pos} vector and the "interval" vector the \code{start} and
#' \code{end} vectors.  The kth index in the "position" vector forms
#' a pair with the kth index in the "interval" vector.  A pair of
#' indexes (i,j) means that \code{pos[i]} belongs to the interval
#' defined by \code{start[j]} and \code{end[j]}.
rcpp_find_matching_intervals <- function(pos, start, end) {
    .Call('miscFun_rcpp_find_matching_intervals', PACKAGE = 'miscFun', pos, start, end)
}

